services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    networks:
      - k6Net
      - grafanaNet
    volumes:
      - ./influxdb:/var/lib/influxdb

  k6:
    image: grafana/k6:latest
    networks:
      - k6Net
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    env_file: .env
    volumes:
      - ./dist:/scripts

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/
    networks:
      - grafanaNet

networks:
  k6Net:
    driver: bridge
  grafanaNet:
    driver: bridge
